### PR TITLE
Move sample.py out of the distribution

### PR DESCRIPTION
**Pull request by briancurtin**
`sample.py` can live inside the docs directory and work fine without being installed. This may require a change on the ReadTheDocs configuration to point it at the included `docs-requirements.txt` file, though I won't know that until this gets merged and built on RTD. Including it now in case it's needed.

### CODE REVIEW

**Comment by briancurtin** [comment]
@eli-schwartz, this probably solves the sample problem, right?

**Comment by briancurtin** [comment]
FWIW, this works locally in that the sample is no longer included in the build, and the docs properly include the sample, so I think it's probably the right move.

**Comment by briancurtin** [comment]
Not currently, but there’s recent activity on https://github.com/rtfd/readthedocs.org/issues/1340 to suggest that may be possible in the future. For now, once I merge this I’ll keep an eye on the RTD build and if it needs a follow up change I’ll do that separately.

**Comment by eli-schwartz** [comment]
Actually https://docs.readthedocs.io/en/latest/features.html#version-control-support-matrix implies you should be able to manually enable RTD for a specific branch, as long as the branch is in the primary repository (which this, of course, is).

Could test the docs build, and then test removing install_requires, before merging to master if I read this right.

**Comment by briancurtin** [comment]
https://deprecation.readthedocs.io/en/fix_sample_installation/ shows this works.

What's the `install_requires` change you mention? I'm guessing you mean to take `unittest2` out of it?

**Comment by eli-schwartz** [comment]
Yes.

**Comment by briancurtin** [comment]
This is now released as 2.0.4: https://pypi.org/project/deprecation/2.0.4/

**Comment by eli-schwartz** [comment]
Thanks!

**Comment by eli-schwartz** [comment]
BTW have you pushed the git tag for this release yet.

**Comment by briancurtin** [comment]
Oops, forgot to push. It's there now.

**Pull request merged**
