### PR TITLE
Add a docstring for message_location

### PR DESCRIPTION
**Pull request by briancurtin**
This change adds an explanation of what message_location can do.

### CODE REVIEW

**Comment by briancurtin** [comment]
@kmuehlbauer can you take a quick look at this? I just realized that message_location wasn't showing up in the docs so this adds it. After this one I'll make the release.

**Comment by briancurtin** [comment]
It also slightly changed `__all__` so `message_location` showed up closer to the decorator in the docs.

**Comment by kmuehlbauer** [comment]
This looks good, but how will this effect the docs? I just sphinxed this, but had nothing in the docs. Maybe I did something wrong while sphinxing.

**Comment by kmuehlbauer** [comment]
@briancurtin My bad. Problem sit's in front of screen. All good! :+1:

**Comment by briancurtin** [comment]
Hah! Thanks, I'll put together the release and comment back here when it's done.

**Comment by briancurtin** [comment]
@kmuehlbauer there you go: https://pypi.org/project/deprecation/2.0/

Thanks for your help on all of this stuff!

**Comment by kmuehlbauer** [comment]
@briancurtin Perfect! No worries, `deprecation`-package is a replacement for one decorator we had in our codebase. But much nicer. Glad, we got this running.

**Comment by kmuehlbauer** [comment]
BTW, we have [deprecation](https://github.com/conda-forge/deprecation-feedstock) packaged within [conda-forge](https://conda-forge.org/).

**Comment by briancurtin** [comment]
Oh cool! :beers:

**Pull request merged**
