### PR TITLE
Migrate from distutils.version to packaging.version

### PR DESCRIPTION
**Pull request by dray92**
{[This post](https://stackoverflow.com/a/11887885)} basically sums up the reason for this change.

`distutils.version.StrictVersion` does not really allow for things like `a.b.c.dev0` and using `LooseVersion` seemed to be a little too casual.

So, when integrating this into libraries, marking something deprecated would cause a bunch of errors in things like tests, if the version isn't _"strict"_.

Thoughts? :)

### CODE REVIEW

**Comment by debosmit** [comment]
Will resolve #9

**Comment by dray92** [comment]
Will resolve #9

**Comment by briancurtin** [comment]
Looks reasonable enough to me, but I'd like to read more about it. I'm currently on vacation until January 8, though I may be able to take a look next week.

**Comment by dray92** [comment]
@briancurtin can we get some traction on this? :)

**Comment by briancurtin** [comment]
Whoops, yes, looking now!

**Pull request merged**
